// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP1tLUvq3DO52bFptmDbMnmyzOFavvGag',
    appId: '1:725332116816:web:c0b3086c44c0210e825855',
    messagingSenderId: '725332116816',
    projectId: 'project-3-bef04',
    authDomain: 'project-3-bef04.firebaseapp.com',
    storageBucket: 'project-3-bef04.appspot.com',
    measurementId: 'G-8M2KW0FFCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk3VBZXirAYD6YNvY5lfi21Wll_s2lUNo',
    appId: '1:725332116816:android:9b47fb6bf44d0420825855',
    messagingSenderId: '725332116816',
    projectId: 'project-3-bef04',
    storageBucket: 'project-3-bef04.appspot.com',
  );
}
